### ISSUE TITLE
The module in both 0.1.0 and 0.2.0 versions does not handle custom descriptions

### ISSUE THREAD

**Issue by cterence** [padok-team/terraform-aws-iam#10]
For a Padok project, we need to import existing IAM roles and policies.

In the 0.1.0 version of the module (that we wanted to use), we cannot set a description for a policy as it's not provided in any way to the resource.
In the 0.2.0 version of the module, the description of the policy is automatically generated.

In both cases, this is not compatible with importing existing policies as a difference in the policy description forces it's replacement during the plan. We do not want to replace the policies as it has a cascade effect on other resources.

We should be able to provide custom descriptions for both versions of the module.

**Comment by DjinnS** [comment]
Hi @cterence,

Feature now available in > v0.3.0 : https://github.com/padok-team/terraform-aws-iam/pull/13
